### ISSUE TITLE
Teams should be balanced according to player level (and item level)

### ISSUE THREAD

**Issue by FrancescoBorzi** [azerothcore/mod-cfbg#27]
We are using

```
CFBG.Include.Avg.Ilvl.Enable = 1
```

but it does not seem to create balanced teams.

We started a 3 vs 3 BG at 10-19 where the teams were:

- TEAM A: 3 players at level 10, 11 and 12
- TEAM B: 2 players at level 13, 18 and 19 

so it was completely unbalanced xD

-------------

I think we need a new config, such as 

```
CFBG.BalancedTeams = 1
```

when enabled, teams should be balanced with levels AND by item level.
 
So that when a new player queues, it will end up with the team having the lowest character level (sum of all players).
If the level is the same, it will end up to the team having the lowest item level (sum of all players).

**Comment by Helias** [comment]
The average item level calculation was totally wrong because it considered the real faction of the player instead of the fake one, so it can never do the right balance.

I implemented this BalanceTeams feature and fixed the average item level calculation.

https://github.com/azerothcore/mod-cfbg/pull/28
