### ISSUE TITLE
10+ players in warsong per faction [$15]

### ISSUE THREAD

**Issue by The-GhostRider** [azerothcore/mod-cfbg#49]
Originally reported https://github.com/chromiecraft/chromiecraft/issues/335

#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [X] 20-29
- [ ] 30-39

##### CURRENT BEHAVIOUR:

10+ players in warsong.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Max players per faction is 10.

##### EXTRA NOTES:

Not sure how this happened.
Happen for both faction.

![Capture d’écran (13)](https://user-images.githubusercontent.com/81832274/113492126-db1d2f80-94d5-11eb-873e-715d121af435.png)
![Capture d’écran (14)](https://user-images.githubusercontent.com/81832274/113492131-dce6f300-94d5-11eb-81f8-f60c89455b5b.png)

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/9d4eebc61fec3b9701ae94292e8d40962804b676

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Winfidonarleyan** [comment]
Cfbg problem, i think

**Comment by Kitzunu** [comment]
In Discord it was confirmed without CFBG module

**Comment by FrancescoBorzi** [comment]
@Winfidonarleyan can you take care of this, please?

**Comment by Shineslippers** [comment]
New issue to it. Not only more people, but unbalance also. https://github.com/chromiecraft/chromiecraft/issues/2316

![WoWScrnShot_111321_060025](https://user-images.githubusercontent.com/89823720/141626074-ca3d23a7-3b37-4a26-aa1e-edcf09e37200.jpg)

**Comment by Eronox** [comment]
> Indeed this is an issue as it should respect the `MaxPlayersPerTeam` value given in `battleground_template`, which by default is `10` for Warsong Gulch. And we haven't changed that value, so it' supposed to be 10.


Doesn't seem to be a matter of flawed logic, per my testing for queue'ing this is my results:

_(WG changed to min/max 1-1 instead of 5-10)_

Players (all level 32)
````
Player1 - Alliance
Player2 - Horde
Player3 - Horde
````

1. Player 2 queues for WSG 
_- No BG_
2. Player 3 queues for WSG
_- No BG_
3. Player 1 queues for WSG
_- BG starts , featuring player 2 & 1_
_- Player3 moved to a new WSG queue_

![image](https://user-images.githubusercontent.com/20321723/147163536-1d5a5c90-a882-4209-b7fa-1ecda3913bab.png)

Instead, this seems to be caused by an edge case somewhere. Like if max queues are met or if something is going weird with premade group queues after the `CONFIG_BATTLEGROUND_INVITATION_TYPE` implementation [2 years ago ](https://github.com/azerothcore/azerothcore-wotlk/commit/b1d102e04b480ff2791d6167ca7891a314dbbcdd)

**Comment by FrancescoBorzi** [comment]
> New issue to it. Not only more people, but unbalance also. [chromiecraft/chromiecraft#2316](https://github.com/chromiecraft/chromiecraft/issues/2316)

we should prioritise any balancing issue,

cc @Hacki95
