### ISSUE TITLE
CFBG.Players.Count.In.Group ??? default option?

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/mod-cfbg#8]
```
#   CFBG.Players.Count.In.Group
#       Description: Maximum players in party for enter queue
#       Default: 3
#
```

Why is it default: 3 and not default: 5??

**Comment by diluh** [comment]
This configuration does not work, if the players join the group they are still separated.

It should allow groups in BG with this configuration active.

**Comment by BarbzYHOOL** [comment]
Ok, so it's buggy, but why default to 3 and not to 5?

**Comment by disclosurez** [comment]
> Ok, so it's buggy, but why default to 3 and not to 5?

to stop premades

**Comment by CosmeF** [comment]
Annyone knows how to enable premades on this module? It would be greately appreciated. For groups of 2 or 3 players would be great.

**Comment by BarbzYHOOL** [comment]
???

**Comment by CosmeF** [comment]
Currently this mod doesn't support premades, even if a couple of players enter the bg queue. It isn't entirely necessary to disband all groups in order to have cross faction bg working, specially if you place the premades first and then fill the rest of the players into the bg. I've seen it in action, so I'm just asking if anyone here has the 'know how', or at least a clue.

**Comment by Yehonal** [comment]
I think it's quite easy to implement, however, premade are dangerous on low-population servers because the system can have hard times to balance the BGs then. But it's definitely a must-have feature

**Comment by mnclaras** [comment]
@Yehonal Do you know how to implement this? There are too much interested people in this option.
